style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/davidalpert/go-git-mob
options:
  # commits:
    # filters:
      # Type:
      #   - build
      #   - feat
      #   - fix
      #   - perf
      #   - refactor
  commit_groups:
    sort_by: Custom
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      test: Test Coverage
      build: Build
      chore: Chore
    title_order:
      - feat
      - fix
      - perf
      - refactor
      - test
      - build
      - chore
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
