name: Pull Request Feedback

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
    - main

permissions:
  # contents: write
  # packages: write
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

    - name: Vale Linter # https://github.com/marketplace/actions/vale-linter
      uses: errata-ai/vale-action@reviewdog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        fail_on_error: true
        files: '["README.md", "CONTRIBUTING.md"]'
        filter_mode: nofilter
        reporter: github-pr-check
        version: 2.17.0

    - name: Install tools
      uses: jdx/mise-action@v2

    - name: Unit tests
      run: |
        task test
